### PR TITLE
Updated SageMaker Instructions

### PR DESCRIPTION
**Pull request by dfreniche**
Added an updated version of the Sagemaker instructions based on the SageMaker post

### CODE REVIEW

**Comment by DominicFrei** [comment]
LGTM 👍

**Comment by joellord** [comment]
The instructions should show an implementation into the library application. The instructions, as provided in this PR, are not relevant to the lab. 
We also need to keep only the screenshots that are absolutely necessary. The instructions, as they are in this PR, are at risk of being out of date very quickly, and we need to manually check at random intervals since we don't own the UI, and don't know when it might change.

**Comment by dfreniche** [comment]
@joellord fair points. But:

- We can add the word "book" when talking about embeddings, and then we'll got the same result I guess. 
- This is less about the lab (because those parts are marked as not part of it but as 'additional' information) and more about showing the magic behind all this.
- re: screenshots. The AWS UI is super confusing and without the screenshots is impossible to follow. 
 
Maybe what we can do is just to point out to your blog post and maintain just that? Although having this SageMaker info here makes the lab more palatable for AWS engagements?

**Comment by joellord** [comment]
* It's not just about books. We're providing the users with an unrelated example in a different programming language. The idea for that section is to provide the instructions so that users can replace using the serverless endpoint with SageMaker. If we provide a random tutorial, we're better off linking to a tutorial in the Dev Center.

* It's a matter of consistency. The Vertex and OpenAI examples integrate with the application, and we added the necessary code to the sample application. If we want the SageMaker example in there, it should follow the same pattern, or else we're not providing the same visibility to this partner as we do with others.

* If the screenshots are absolutely needed (i.e., there is no way to do it with the CLI), then they need to be updated, as they are currently already out of date. While I agree that AWS has the most confusing UI possible, I don't think all of these screenshots are necessary. At a quick glance, most of them can be replaced by an instruction. With complex UIs, screenshots are even more confusing than written instructions when the screenshots don't match the actual UI. They also take up a lot of room on an already full screen during the in-person labs.

**Comment by dfreniche** [comment]
After some thinking, we're going to close this PR unmerged and just point to the [SageMaker post in DevHub](https://www.mongodb.com/developer/products/atlas/amazon-sagemaker-and-mongodb-vector-search-part-1/), instead of replicating it here.

**Pull request closed without merging**
